# Generated by Django 4.1.3 on 2022-11-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
